### ISSUE TITLE
possible error in the script?

### ISSUE THREAD

**Issue by ComradePashka** [samdark/realpath_cache_tuner#4]
I tried to run script and got:

```
A non well formed numeric value encountered
```
Line https://github.com/samdark/realpath_cache_tuner/blob/86b60d3dd95062ef2154e6b8ea37ff2506a815dd/realpath_cache_tuner.php#L12 gets last symbol and transforms it to lowercase, but whole string in such case is not transformed and contain that symbol!

And next lines:
https://github.com/samdark/realpath_cache_tuner/blob/86b60d3dd95062ef2154e6b8ea37ff2506a815dd/realpath_cache_tuner.php#L13-L20

what is the difference? any case inside switch do exactly same task.

**UPD** oops, I missed there are no `break` statement. ok, anyway `$value` is still seems incorrect for calculations.

**UPD2** I think next code after line #12 may fix that issue:

```
if ($last) $value = substr($value, 0, strlen($value) - 1);
```

**Comment by samdark** [comment]
What do you have in `$value` when it errors?

**Comment by ComradePashka** [comment]
4096K

 -- string returned by `ini_get('realpath_cache_size')`

**Comment by samdark** [comment]
Fixed with https://github.com/samdark/realpath_cache_tuner/commit/1d84ab844af218b63e5e367d139cec330ae8647d. Thanks for reporting!
